---
- name: Cisco IOS config
  hosts: ios-rt1
  gather_facts: false
  connection: local
  vars:
    commands: []
    no_commands: []

  tasks:
    - include_vars: main.yml

    - name: Capture show command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: _config_asis

    - name: Debug config asis
      debug:
        var: _config_asis.stdout_lines

    - name: Debug config asis
      debug:
        var: config_tobe

    - name: Set variable for policy services / applications
      set_fact:
        commands: "{{ commands + [item] }}"
      loop: "{{ config_tobe }}"
      when: item not in _config_asis.stdout_lines

    - name: Set variable for policy services / applications
      set_fact:
        commands: "{{ no_commands + ['no ' + item] }}"
      loop: "{{ _config_asis.stdout_lines }}"
      when: item not in config_tobe

    - name: Debug commands
      debug:
        var: _commands

    - name: Debug no commands
      debug:
        var: _no_commands
