---
- name: Cisco IOS config
  hosts: ios-rt1
  gather_facts: false
  connection: local
  vars:
    cisco_commands: []
    cisco_no_commands: []

  tasks:
    - include_vars: main.yml

    - name: Capture show command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: config_asis

    - name: Debug config asis
      debug:
        var: config_asis.stdout_lines

    - name: Debug config asis
      debug:
        var: config_tobe

    - name: Set commands to add
      set_fact:
        cisco_commands: "{{ cisco_commands + [item] }}"
      loop: "{{ config_tobe }}"
      when: item not in config_asis.stdout_lines

    - name: Set commands to remove (no)
      set_fact:
        cisco_no_commands: "{{ cisco_no_commands + [item] }}"
      loop: "{{ config_asis.stdout_lines }}"
      when: item not in config_tobe

    - name: Debug commands
      debug:
        var: cisco_commands

    - name: Debug no commands
      debug:
        var: cisco_no_commands

    #fw_conf_lines: "{{ fw_conf_lines + ['set security policies from-zone ' + _src_zone + ' to-zone ' + _dest_zone + ' policy ' + _rule.name + ' match application ' + srx_services[_service] ] }}"
