---
- name: Cisco IOS config
  hosts: ios-rt1
  gather_facts: false
  connection: local
  vars:
    commands: []
    no_commands: []

  tasks:
    - include_vars: main.yml

    - name: Capture show command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: _config_asis

    - name: Debug
      debug:
        var: _config_asis.stdout_lines

    - name: Debug
      debug:
        var: item
      with_nested:
        - "{{ _config_asis.stdout_lines }}"
        - "{{ config_tobe }}"


    # - name: Set variable for policy services / applications
    #   set_fact:
    #     fw_conf_lines: "{{ fw_conf_lines + ['set security policies from-zone ' + _src_zone + ' to-zone ' + _dest_zone + ' policy ' + _rule.name + ' match application ' + srx_services[_service] ] }}"


