---
- name: Cisco IOS config
  hosts: ios-rt1
  gather_facts: false
  connection: local
  vars:
    cisco_commands: []
    cisco_no_commands: []

  tasks:
    - include_vars: main.yml

    - name: Capture show command output
      cisco.ios.ios_command:
        commands: "show running-config all | include radius"
      register: radius_asis

    - name: Debug radius config asis
      debug:
        var: radius_asis.stdout_lines[0]

    - name: Debug radius config tobe (vars/main.yml)
      debug:
        var: radius_tobe

    - name: Select commands to add
      set_fact:
        cisco_commands: "{{ cisco_commands + [item] }}"
      loop: "{{ radius_tobe }}"
      when: item not in radius_asis.stdout_lines[0]

    - name: Select commands to remove (no)
      set_fact:
        cisco_no_commands: "{{ cisco_no_commands + ['no ' + item] }}"
      loop: "{{ radius_asis.stdout_lines[0] }}"
      when: item not in radius_tobe

    - name: Debug commands
      debug:
        var: cisco_commands

    - name: Debug no commands
      debug:
        var: cisco_no_commands

    - name: Run no commands
      cisco.ios.ios_config:
        lines: "{{ cisco_no_commands }}"
      when: cisco_no_commands|length>0 
      #parents: []

    - name: Run commands
      cisco.ios.ios_config:
        lines: "{{ cisco_commands }}"
        when: cisco_commands|length>0 
        #parents: []
