---

- name: Cisco IOS config vlans
  hosts: ios-sw1
  gather_facts: no
  tasks:

  - name: Cisco IOS Include VLAN variables
    include_vars: main.yml

  - name: Cisco IOS Config vlans
    cisco.ios.ios_vlans:
      config: "{{ vlans_tobe }}"
      state: merged
      #state: overridden
    register: _vlan
    become: yes

  - name: Cisco IOS Debug VLANs before
    debug:
      var: _vlan.before

  - name: Cisco IOS Debug VLANs command
    debug:
      var: _vlan.commands

  - name: Cisco IOS Debug VLAN after
    debug:
      var: _vlan.after

  - name: Save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified
      